This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file /Users/elisabeth/repos/NER-german-telegram/thesis/.texpadtmp/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/elisabeth/repos/NER-german-telegram/thesis/.texpadtmp/thesis.acn....done (168 entries accepted, 0 rejected).
Sorting entries....done (1303 comparisons).
Generating output file /Users/elisabeth/repos/NER-german-telegram/thesis/.texpadtmp/thesis.acr....done (75 lines written, 0 warnings).
Output written in /Users/elisabeth/repos/NER-german-telegram/thesis/.texpadtmp/thesis.acr.
Transcript written in /Users/elisabeth/repos/NER-german-telegram/thesis/.texpadtmp/thesis.alg.
